# POST http://localhost:7070/api/users
# Content-Type: application/json

# {
#     "name": "Racheal Kuranchie",
#     "email": "kuranchieracheal@gmail.com",
#     "password": "123456"
# }

# POST http://localhost:7070/api/login
# Content-Type: application/json

# {
#     "email": "kuranchieracheal@gmail.com",
#     "password": "123456"
# }


GET http://localhost:7070/api/property/search/airport/singleroom/800



